import type { IncentiveRule } from "./types";

const createdAt = "2026-06-30T00:00:00.000Z";
const effectiveDate = "2026-07-01";
const createdByName = "CareBearBooks Admin";

function seedRule(rule: Omit<IncentiveRule, "createdAt" | "updatedAt" | "createdByName">): IncentiveRule {
  return {
    ...rule,
    createdByName,
    createdAt,
    updatedAt: createdAt
  };
}

export const seededIncentiveRules: IncentiveRule[] = [
  seedRule({
    id: "rule-general-meet-salary-increment",
    ruleKey: "general-meet-salary-increment",
    ruleName: "General Meet Salary Increment",
    description:
      "Default Meet-only permanent monthly salary increment for Sales, Payroll, Bookkeeping, Taxes, and Processes unless a special rule applies.",
    department: "Any",
    workArea: "Sales, Payroll, Bookkeeping, Taxes, Processes",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "rating_system",
    triggerMetric: "Meet rating",
    triggerComparison: "equals",
    triggerThresholdUnit: "Meet only",
    triggerFrequency: "Monthly",
    triggerMessage: "Meet rating qualifies for default salary increment.",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isUncapped: true,
    isOneTime: false,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: {
      ratingSystem: "Meet only",
      removedRatings: ["Exceeding", "Outstanding"],
      badFuturePeriodDoesNotReducePastIncrement: true
    },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    notes: "Bad future periods should not reduce past earned increments.",
    effectiveDate
  }),

  seedRule({
    id: "rule-sales-independent-client-acquisition",
    ruleKey: "sales-independent-client-acquisition",
    ruleName: "Independent Client Acquisition",
    description: "Sales employee independently acquires and onboards a paying client.",
    department: "Sales",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "client_acquisition",
    triggerMetric: "Paying clients independently acquired",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per client",
    payoutType: "fixed",
    amount: 3500,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_per_client",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    requiresPayingClient: true,
    notes: "One-time per client.",
    effectiveDate
  }),
  seedRule({
    id: "rule-sales-acquisition-andrew-support",
    ruleKey: "sales-acquisition-andrew-support",
    ruleName: "Acquisition With Andrew Support",
    description: "Client acquired or onboarded with Andrew support; onboarder receives the configured amount.",
    department: "Sales",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "client_acquisition_with_support",
    triggerMetric: "Paying clients acquired with Andrew support",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per client",
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_per_client",
    supportType: "Andrew support",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    requiresPayingClient: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-sales-acquisition-consultation-support",
    ruleKey: "sales-acquisition-consultation-support",
    ruleName: "Acquisition With Consultation Staff Support",
    description:
      "Client acquired or onboarded with consultation staff support; onboarder payout is separate from consultant/helper claim.",
    department: "Sales",
    workArea: "Sales + Processes",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "client_acquisition_with_consultation_support",
    triggerMetric: "Paying clients acquired with consultation support",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per client",
    payoutType: "split",
    amount: 2000,
    currency: "KSH",
    splitGroupKey: "consultation-supported-acquisition",
    splitRole: "Onboarder",
    splitAmount: 1500,
    splitCurrency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "split_acquisition_support",
    supportType: "Consultation staff support",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    requiresPayingClient: true,
    notes:
      "Consultant/helper must claim separately under Processes. Onboarder must not see the total combined KSh 3,500 payout.",
    effectiveDate
  }),
  seedRule({
    id: "rule-sales-tax-only-client-andrew-support",
    ruleKey: "sales-tax-only-client-andrew-support",
    ruleName: "Tax-Only Client With Andrew Support",
    description: "Tax-only client acquired with Andrew support.",
    department: "Taxes",
    workArea: "Sales / Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "tax_only_client_acquisition",
    triggerMetric: "Tax-only paying clients acquired with Andrew support",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per client",
    payoutType: "fixed",
    amount: 500,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_per_client",
    supportType: "Andrew support",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    requiresPayingClient: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-cross-department-referral",
    ruleKey: "cross-department-referral",
    ruleName: "Cross-Department Referral",
    description: "Any employee refers a lead that converts to a paying client.",
    department: "Any",
    claimType: "Employee Claim",
    ruleCategory: "Referral",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "converted_referral",
    triggerMetric: "Converted paying client referrals",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "converted client",
    triggerFrequency: "Per client",
    payoutType: "fixed",
    amount: 1500,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_per_converted_referral",
    employeeBasedOrTeamBased: "Employee",
    stackable: true,
    requiresApproval: true,
    requiresPayingClient: true,
    notes: "Lead should be logged before contact. One referral bonus per client. Stackable if configured.",
    effectiveDate
  }),
  seedRule({
    id: "rule-sales-performance-salary-increment",
    ruleKey: "sales-performance-salary-increment",
    ruleName: "Sales Performance Salary Increment",
    description: "Sales employee meets department threshold for clients, revenue, and retention.",
    department: "Sales",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "sales_performance_threshold",
    triggerMetric: "New paying clients, new revenue, retention at 60 days",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 3,
    triggerThresholdUnit: "new paying clients",
    triggerFrequency: "Monthly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: {
      minimumNewPayingClients: 3,
      minimumNewRevenue: 50000,
      retentionThresholdPercent: 90,
      retentionDays: 60,
      ratingSystem: "Meet only"
    },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    requiresPayingClient: true,
    requiresActiveClient: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-sales-ten-client-salary-milestone",
    ruleKey: "sales-ten-client-salary-milestone",
    ruleName: "Sales 10-Client Salary Milestone",
    description: "Every 10 active or paying clients by the same employee from July 2026 onward triggers review.",
    department: "Sales",
    claimType: "Automatic Trigger",
    ruleCategory: "Salary Increment",
    incentiveType: "Review",
    status: "Active",
    isActive: true,
    triggerType: "active_client_milestone",
    triggerMetric: "Active/paying clients by same employee",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 10,
    triggerThresholdUnit: "active/paying clients",
    triggerStartDate: "2026-07-01",
    triggerFrequency: "Every milestone",
    automaticTriggerEnabled: true,
    triggerMessage: "Team due for Salary increase. 10 clients reached!",
    payoutType: "milestone",
    amount: 5000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isUncapped: true,
    isMonthly: true,
    formulaType: "salary_milestone",
    formulaKey: "sales_active_client_salary_milestone",
    formulaVariables: {
      milestoneClientCount: 10,
      milestoneIncrementAmount: 5000,
      churnedClientsCount: false
    },
    employeeBasedOrTeamBased: "Employee",
    requiresActiveClient: true,
    requiresPayingClient: true,
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-payroll-onboarding-bonus",
    ruleKey: "payroll-onboarding-bonus",
    ruleName: "Payroll Onboarding Bonus",
    description: "New payroll client successfully onboarded.",
    department: "Payroll",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "payroll_client_onboarded",
    triggerMetric: "New payroll clients onboarded",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per client",
    payoutType: "fixed",
    amount: 500,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_per_client",
    serviceType: "Payroll",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "Evidence: first paystubs submission or screenshot of payroll payment/payroll run.",
    effectiveDate
  }),
  seedRule({
    id: "rule-payroll-accuracy-bonus",
    ruleKey: "payroll-accuracy-bonus",
    ruleName: "Payroll Accuracy Bonus",
    description: "Zero payroll errors or corrections during the quarter.",
    department: "Payroll",
    claimType: "Manager Verified",
    ruleCategory: "Accuracy",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "zero_errors",
    triggerMetric: "Payroll errors/corrections",
    triggerComparison: "equals",
    triggerThresholdValue: 0,
    triggerThresholdUnit: "errors",
    triggerPeriod: "Quarterly",
    triggerFrequency: "Quarterly",
    automaticTriggerEnabled: true,
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    requiresTeamLeaderVerification: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-payroll-run-completion-bonus",
    ruleKey: "payroll-run-completion-bonus",
    ruleName: "Payroll Run Completion Bonus",
    description: "All assigned payroll runs completed or submitted on time.",
    department: "Payroll",
    claimType: "Manager Verified",
    ruleCategory: "Completion",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "payroll_run_completion",
    triggerMetric: "Assigned payroll runs completed/submitted on schedule",
    triggerComparison: "equals",
    triggerThresholdValue: 100,
    triggerThresholdUnit: "percent complete",
    triggerPeriod: "Quarterly",
    triggerFrequency: "Quarterly",
    payoutType: "fixed",
    amount: 1500,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    notes: "Deadline basis is each client's agreed payroll schedule. Use payroll run completion wording.",
    effectiveDate
  }),
  seedRule({
    id: "rule-payroll-client-retention-bonus",
    ruleKey: "payroll-client-retention-bonus",
    ruleName: "Payroll Client Retention Bonus",
    description: "Payroll client reaches 12-month anniversary and remains active.",
    department: "Payroll",
    claimType: "Automatic Trigger",
    ruleCategory: "Retention",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "client_retention_anniversary",
    triggerMetric: "Active payroll client anniversary",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 12,
    triggerThresholdUnit: "months",
    triggerFrequency: "Every 12 months",
    automaticTriggerEnabled: true,
    payoutType: "fixed",
    amount: 1500,
    currency: "KSH",
    payoutFrequency: "Every 12 months",
    repeatIntervalValue: 12,
    repeatIntervalUnit: "months",
    formulaType: "fixed",
    formulaKey: "fixed_retention_anniversary",
    requiresActiveClient: true,
    employeeBasedOrTeamBased: "Employee",
    notes: "Goes to actual worker. If worker changed, split pro-rata by months handled.",
    effectiveDate
  }),
  seedRule({
    id: "rule-payroll-salary-increment",
    ruleKey: "payroll-salary-increment",
    ruleName: "Payroll Salary Increment",
    description: "Zero errors, all assigned runs completed on schedule, and assigned new payroll clients onboarded.",
    department: "Payroll",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "payroll_performance_threshold",
    triggerMetric: "Zero errors, schedule completion, assigned onboarding",
    triggerComparison: "completed",
    triggerFrequency: "Monthly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: { ratingSystem: "Meet only" },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-bookkeeping-accuracy-bonus",
    ruleKey: "bookkeeping-accuracy-bonus",
    ruleName: "Bookkeeping Accuracy Bonus",
    description: "Zero client-reported errors or reconciliation corrections during the quarter.",
    department: "Bookkeeping",
    claimType: "Manager Verified",
    ruleCategory: "Accuracy",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "zero_client_reported_errors",
    triggerMetric: "Client-reported errors/reconciliation corrections",
    triggerComparison: "equals",
    triggerThresholdValue: 0,
    triggerThresholdUnit: "errors",
    triggerPeriod: "Quarterly",
    triggerFrequency: "Quarterly",
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresTeamLeaderVerification: true,
    notes: "Self-corrected errors before client delivery do not disqualify.",
    effectiveDate
  }),
  seedRule({
    id: "rule-bookkeeping-turnaround-bonus",
    ruleKey: "bookkeeping-turnaround-bonus",
    ruleName: "Bookkeeping Turnaround Bonus",
    description: "All monthly reports delivered on or before agreed dates for the full quarter.",
    department: "Bookkeeping",
    claimType: "Manager Verified",
    ruleCategory: "Completion",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "report_turnaround",
    triggerMetric: "Monthly reports delivered on or before agreed dates",
    triggerComparison: "equals",
    triggerThresholdValue: 100,
    triggerThresholdUnit: "percent on time",
    triggerPeriod: "Full quarter",
    triggerFrequency: "Quarterly",
    payoutType: "fixed",
    amount: 1500,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-books-cleanup-standard",
    ruleKey: "books-cleanup-standard",
    ruleName: "Books Cleanup Standard",
    description: "Cleanup completed within agreed timeframe for up to 6 months backdated.",
    department: "Bookkeeping",
    claimType: "Employee Claim",
    ruleCategory: "Cleanup",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "books_cleanup_completed",
    triggerMetric: "Backdated cleanup months",
    triggerComparison: "less_than_or_equal",
    triggerThresholdValue: 6,
    triggerThresholdUnit: "months",
    triggerFrequency: "One-time per client",
    payoutType: "fixed",
    amount: 1000,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_cleanup_bonus",
    complexityLevel: "Standard",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    notes: "Requires team leader sign-off.",
    effectiveDate
  }),
  seedRule({
    id: "rule-books-cleanup-complex",
    ruleKey: "books-cleanup-complex",
    ruleName: "Books Cleanup Complex",
    description: "Complex cleanup completed within agreed timeframe for 7+ months or multiple accounts.",
    department: "Bookkeeping",
    claimType: "Employee Claim",
    ruleCategory: "Cleanup",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "books_cleanup_completed",
    triggerMetric: "Backdated cleanup months or multiple accounts",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 7,
    triggerThresholdUnit: "months",
    triggerFrequency: "One-time per client",
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "One-time per client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_cleanup_bonus",
    complexityLevel: "Complex",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    notes: "Applies to 7+ months or multiple accounts. Requires team leader sign-off.",
    effectiveDate
  }),
  seedRule({
    id: "rule-bookkeeping-client-retention-bonus",
    ruleKey: "bookkeeping-client-retention-bonus",
    ruleName: "Bookkeeping Client Retention Bonus",
    description: "Bookkeeping client reaches 12-month anniversary and remains active.",
    department: "Bookkeeping",
    claimType: "Automatic Trigger",
    ruleCategory: "Retention",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "client_retention_anniversary",
    triggerMetric: "Active bookkeeping client anniversary",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 12,
    triggerThresholdUnit: "months",
    triggerFrequency: "Every 12 months",
    automaticTriggerEnabled: true,
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "Every 12 months",
    repeatIntervalValue: 12,
    repeatIntervalUnit: "months",
    formulaType: "fixed",
    formulaKey: "fixed_retention_anniversary",
    requiresActiveClient: true,
    employeeBasedOrTeamBased: "Employee",
    notes: "Goes to actual worker. If worker changed, split pro-rata by months handled.",
    effectiveDate
  }),
  seedRule({
    id: "rule-combined-bookkeeping-payroll-retention",
    ruleKey: "combined-bookkeeping-payroll-retention",
    ruleName: "Combined Bookkeeping + Payroll Retention",
    description: "Same client has both services and reaches a 12-month active anniversary.",
    department: "Bookkeeping",
    workArea: "Bookkeeping + Payroll",
    claimType: "Automatic Trigger",
    ruleCategory: "Retention",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "combined_service_retention_anniversary",
    triggerMetric: "Active client with bookkeeping and payroll services",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 12,
    triggerThresholdUnit: "months",
    triggerFrequency: "Every 12 months",
    automaticTriggerEnabled: true,
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Every 12 months",
    repeatIntervalValue: 12,
    repeatIntervalUnit: "months",
    formulaType: "fixed",
    formulaKey: "fixed_retention_anniversary",
    requiresActiveClient: true,
    employeeBasedOrTeamBased: "Either",
    notes: "Goes to assigned worker(s), split by work/months if needed.",
    effectiveDate
  }),
  seedRule({
    id: "rule-bookkeeping-salary-increment",
    ruleKey: "bookkeeping-salary-increment",
    ruleName: "Bookkeeping Salary Increment",
    description: "Zero client errors, on-time reports, and 100% assigned clients retained.",
    department: "Bookkeeping",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "bookkeeping_performance_threshold",
    triggerMetric: "Zero errors, on-time reporting, assigned client retention",
    triggerComparison: "completed",
    triggerFrequency: "Monthly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: { ratingSystem: "Meet only", assignedClientRetentionPercent: 100 },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-processes-consultation-support-bonus",
    ruleKey: "processes-consultation-support-bonus",
    ruleName: "Consultation Support Bonus",
    description: "Consultation staff helped onboard or support client acquisition.",
    department: "Processes",
    claimType: "Employee Claim",
    ruleCategory: "Acquisition",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "consultation_support",
    triggerMetric: "Supported client acquisitions",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1,
    triggerThresholdUnit: "client",
    triggerFrequency: "Per supported client",
    payoutType: "fixed",
    amount: 1500,
    currency: "KSH",
    payoutFrequency: "One-time per supported client",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_consultation_support",
    supportType: "Consultant/helper",
    splitGroupKey: "consultation-supported-acquisition",
    splitRole: "Consultant/helper",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "Claimed separately by consultant/helper, not by onboarder.",
    effectiveDate
  }),
  seedRule({
    id: "rule-processes-model-submission-threshold",
    ruleKey: "processes-model-submission-threshold",
    ruleName: "Model Submission Threshold",
    description: "Models completed, tested, approved, and deployed count toward Processes salary increment threshold.",
    department: "Processes",
    claimType: "Manager Verified",
    ruleCategory: "Threshold",
    incentiveType: "Threshold",
    status: "Active",
    isActive: true,
    triggerType: "model_submission",
    triggerMetric: "Completed/tested/approved/deployed models",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 2,
    triggerThresholdUnit: "models",
    triggerFrequency: "Salary increment period",
    payoutType: "not-specified",
    formulaType: "threshold_only",
    formulaKey: "processes_model_threshold",
    formulaVariables: {
      triggerCount: 2,
      requiredStates: ["completed", "tested", "approved", "deployed"],
      deploymentDestination: ["clients", "company", "internal use"]
    },
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "Direct cash payout not specified.",
    effectiveDate
  }),
  seedRule({
    id: "rule-processes-client-query-response-threshold",
    ruleKey: "processes-client-query-response-threshold",
    ruleName: "Client Query Response Threshold",
    description: "Client queries responded to within 24 hours count toward Processes salary increment threshold.",
    department: "Processes",
    claimType: "Manager Verified",
    ruleCategory: "Threshold",
    incentiveType: "Threshold",
    status: "Active",
    isActive: true,
    triggerType: "query_response_time",
    triggerMetric: "Client query response time",
    triggerComparison: "less_than_or_equal",
    triggerThresholdValue: 24,
    triggerThresholdUnit: "hours",
    triggerFrequency: "Salary increment period",
    payoutType: "not-specified",
    formulaType: "threshold_only",
    formulaKey: "processes_query_response_threshold",
    formulaVariables: { responseWindowHours: 24 },
    employeeBasedOrTeamBased: "Employee",
    notes: "Direct payout not specified; counts toward salary increment threshold.",
    effectiveDate
  }),
  seedRule({
    id: "rule-processes-research-quality-threshold",
    ruleKey: "processes-research-quality-threshold",
    ruleName: "Research Quality / Escalation-Free Threshold",
    description: "Zero advice escalations or reversals due to inaccuracy count toward Processes increment threshold.",
    department: "Processes",
    claimType: "Manager Verified",
    ruleCategory: "Threshold",
    incentiveType: "Threshold",
    status: "Active",
    isActive: true,
    triggerType: "research_quality",
    triggerMetric: "Advice escalations/reversals due to inaccuracy",
    triggerComparison: "equals",
    triggerThresholdValue: 0,
    triggerThresholdUnit: "escalations/reversals",
    triggerFrequency: "Salary increment period",
    payoutType: "not-specified",
    formulaType: "threshold_only",
    formulaKey: "processes_research_quality_threshold",
    formulaVariables: { escalationFreeRequired: true },
    employeeBasedOrTeamBased: "Employee",
    notes: "Direct payout not specified; counts toward salary increment threshold.",
    effectiveDate
  }),
  seedRule({
    id: "rule-processes-salary-increment",
    ruleKey: "processes-salary-increment",
    ruleName: "Processes Salary Increment",
    description:
      "Queries within 24 hours, zero escalations/reversals, and two models completed/tested/approved/deployed.",
    department: "Processes",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "processes_performance_threshold",
    triggerMetric: "Query response, research quality, and model deployment thresholds",
    triggerComparison: "completed",
    triggerFrequency: "Monthly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: {
      responseWindowHours: 24,
      escalationFreeRequired: true,
      requiredModelCount: 2,
      ratingSystem: "Meet only"
    },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-tax-return-general-reward",
    ruleKey: "tax-return-general-reward",
    ruleName: "Tax Return General Reward",
    description: "Tax return completed, EF accepted, and payment received.",
    department: "Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Tax Filing",
    incentiveType: "Formula",
    status: "Active",
    isActive: true,
    triggerType: "tax_return_completed_paid",
    triggerMetric: "Billed amount for accepted and paid return",
    triggerComparison: "completed",
    triggerFrequency: "Per accepted filing",
    payoutType: "percentage",
    percentageRate: 10,
    payoutFrequency: "Per return / accepted filing",
    formulaType: "percentage",
    formulaKey: "percentage_of_billed_amount",
    formulaVariables: { billedAmountPercentageRate: 10 },
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    requiresPaymentReceived: true,
    requiresEfAccepted: true,
    notes: "Evidence: EF accepted screenshot plus payment received email/screenshot.",
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-1040-additional-reward",
    ruleKey: "tax-1040-additional-reward",
    ruleName: "1040 Additional Reward",
    description: "Additional reward for 1040 returns billed over the configured USD threshold.",
    department: "Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Tax Filing",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "tax_return_threshold",
    triggerMetric: "1040 billed amount",
    triggerComparison: "greater_than",
    triggerThresholdValue: 250,
    triggerThresholdUnit: "USD billed",
    triggerFrequency: "Per return / accepted filing",
    payoutType: "fixed",
    amount: 500,
    currency: "KSH",
    payoutFrequency: "Per return / accepted filing",
    formulaType: "fixed",
    formulaKey: "tax_form_threshold_bonus",
    formulaVariables: { billingThreshold: 250, billingThresholdCurrency: "USD" },
    formType: "1040",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresPaymentReceived: true,
    requiresEfAccepted: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-non-1040-additional-reward",
    ruleKey: "tax-non-1040-additional-reward",
    ruleName: "Non-1040 Additional Reward",
    description: "Additional reward for any form other than 1040 billed over the configured USD threshold.",
    department: "Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Tax Filing",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "tax_return_threshold",
    triggerMetric: "Non-1040 billed amount",
    triggerComparison: "greater_than",
    triggerThresholdValue: 750,
    triggerThresholdUnit: "USD billed",
    triggerFrequency: "Per return / accepted filing",
    payoutType: "fixed",
    amount: 1000,
    currency: "KSH",
    payoutFrequency: "Per return / accepted filing",
    formulaType: "fixed",
    formulaKey: "tax_form_threshold_bonus",
    formulaVariables: { billingThreshold: 750, billingThresholdCurrency: "USD" },
    formType: "Non-1040",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresPaymentReceived: true,
    requiresEfAccepted: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-accuracy-bonus",
    ruleKey: "tax-accuracy-bonus",
    ruleName: "Tax Accuracy Bonus",
    description: "Zero IRS corrections or client-reported errors during the quarter.",
    department: "Taxes",
    claimType: "Manager Verified",
    ruleCategory: "Accuracy",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "zero_tax_errors",
    triggerMetric: "IRS corrections or client-reported errors",
    triggerComparison: "equals",
    triggerThresholdValue: 0,
    triggerThresholdUnit: "errors",
    triggerPeriod: "Quarterly",
    triggerFrequency: "Quarterly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    requiresTeamLeaderVerification: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-deadline-adherence-bonus",
    ruleKey: "tax-deadline-adherence-bonus",
    ruleName: "Tax Deadline Adherence Bonus",
    description: "Zero late filings for all clients in the quarter.",
    department: "Taxes",
    claimType: "Manager Verified",
    ruleCategory: "Completion",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "zero_late_filings",
    triggerMetric: "Late filings",
    triggerComparison: "equals",
    triggerThresholdValue: 0,
    triggerThresholdUnit: "late filings",
    triggerPeriod: "Quarterly",
    triggerFrequency: "Quarterly",
    payoutType: "fixed",
    amount: 2000,
    currency: "KSH",
    payoutFrequency: "Quarterly",
    isQuarterly: true,
    formulaType: "fixed",
    formulaKey: "fixed_quarterly_bonus",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-complex-return-standard",
    ruleKey: "tax-complex-return-standard",
    ruleName: "Complex Return Standard",
    description: "Return pre-approved as complex before work begins.",
    department: "Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Tax Filing",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "complex_return_preapproved",
    triggerMetric: "Pre-approved complex returns",
    triggerComparison: "completed",
    triggerFrequency: "One-time per return",
    payoutType: "fixed",
    amount: 500,
    currency: "KSH",
    payoutFrequency: "One-time per return",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_complex_return_bonus",
    complexityLevel: "Standard",
    employeeBasedOrTeamBased: "Employee",
    requiresPreapproval: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-tax-complex-return-highly-complex",
    ruleKey: "tax-complex-return-highly-complex",
    ruleName: "Complex Return Highly Complex",
    description: "Multi-state or business + personal return pre-approved before work begins.",
    department: "Taxes",
    claimType: "Employee Claim",
    ruleCategory: "Tax Filing",
    incentiveType: "Bonus",
    status: "Active",
    isActive: true,
    triggerType: "complex_return_preapproved",
    triggerMetric: "Pre-approved highly complex returns",
    triggerComparison: "completed",
    triggerFrequency: "One-time per return",
    payoutType: "fixed",
    amount: 1000,
    currency: "KSH",
    payoutFrequency: "One-time per return",
    isOneTime: true,
    formulaType: "fixed",
    formulaKey: "fixed_complex_return_bonus",
    complexityLevel: "Highly complex",
    employeeBasedOrTeamBased: "Employee",
    requiresPreapproval: true,
    notes: "Applies to multi-state or business + personal returns.",
    effectiveDate
  }),
  seedRule({
    id: "rule-taxes-salary-increment",
    ruleKey: "taxes-salary-increment",
    ruleName: "Taxes Salary Increment",
    description: "Zero IRS/client errors, zero late filings, managed caseload, and at least one complex return.",
    department: "Taxes",
    claimType: "Manager Verified",
    ruleCategory: "Salary Increment",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "taxes_performance_threshold",
    triggerMetric: "Errors, late filings, caseload, complex returns",
    triggerComparison: "completed",
    triggerFrequency: "Monthly",
    payoutType: "fixed",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_salary_increment",
    formulaVariables: { minimumComplexReturns: 1, ratingSystem: "Meet only" },
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-billing-collection-payout",
    ruleKey: "billing-collection-payout",
    ruleName: "Billing Collection Payout",
    description: "Collection percentage payout with floor, full payout threshold, and max payout.",
    department: "Billing",
    claimType: "Automatic Trigger",
    ruleCategory: "Billing Collection",
    incentiveType: "Formula",
    status: "Active",
    isActive: true,
    triggerType: "collection_percentage",
    triggerMetric: "Collection percentage",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 95,
    triggerThresholdUnit: "percent",
    triggerFrequency: "Simulation period",
    automaticTriggerEnabled: true,
    payoutType: "billing",
    maxPayoutAmount: 5000,
    maxPayoutCurrency: "KSH",
    payoutFrequency: "Simulation period",
    formulaType: "billing_collection",
    formulaKey: "billing_collection_linear_payout",
    formulaVariables: {
      collectionFloorPercent: 95,
      fullPayoutPercent: 100,
      maxPayout: 5000,
      maxPayoutCurrency: "KSH"
    },
    employeeBasedOrTeamBased: "Team",
    requiresApproval: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-marketing-youtube-video-views",
    ruleKey: "marketing-youtube-video-views",
    ruleName: "YouTube Video Views Incentive",
    description: "For every full view block, pay the face/person and editor amounts from the rule.",
    department: "Marketing",
    claimType: "Employee Claim",
    ruleCategory: "Marketing Views",
    incentiveType: "Formula",
    status: "Active",
    isActive: true,
    triggerType: "video_views",
    triggerMetric: "YouTube video views",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 500,
    triggerThresholdUnit: "views",
    triggerFrequency: "One-time per view block",
    payoutType: "milestone",
    payoutFrequency: "One-time per view block",
    isOneTime: true,
    formulaType: "marketing_view_blocks",
    formulaKey: "marketing_view_block_rewards",
    formulaVariables: {
      viewThreshold: 500,
      facePersonReward: 1000,
      editorReward: 500,
      currency: "KSH"
    },
    platform: "YouTube",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-marketing-tiktok-video-views",
    ruleKey: "marketing-tiktok-video-views",
    ruleName: "TikTok Video Views Incentive",
    description: "For every full view block, pay the face/person and editor amounts from the rule.",
    department: "Marketing",
    claimType: "Employee Claim",
    ruleCategory: "Marketing Views",
    incentiveType: "Formula",
    status: "Active",
    isActive: true,
    triggerType: "video_views",
    triggerMetric: "TikTok video views",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 500,
    triggerThresholdUnit: "views",
    triggerFrequency: "One-time per view block",
    payoutType: "milestone",
    payoutFrequency: "One-time per view block",
    isOneTime: true,
    formulaType: "marketing_view_blocks",
    formulaKey: "marketing_view_block_rewards",
    formulaVariables: {
      viewThreshold: 500,
      facePersonReward: 1000,
      editorReward: 500,
      currency: "KSH"
    },
    platform: "TikTok",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-marketing-youtube-subscriber-milestone",
    ruleKey: "marketing-youtube-subscriber-milestone",
    ruleName: "YouTube Subscriber Milestone Increment",
    description: "Every subscriber milestone qualifies top editors and faces/contributors for permanent increment review.",
    department: "Marketing",
    claimType: "Automatic Trigger",
    ruleCategory: "Marketing Milestone",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "subscriber_milestone",
    triggerMetric: "YouTube subscribers",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 1000,
    triggerThresholdUnit: "subscribers",
    triggerFrequency: "Every milestone",
    automaticTriggerEnabled: true,
    payoutType: "milestone",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "salary_milestone",
    formulaKey: "marketing_subscriber_increment",
    formulaVariables: {
      subscriberMilestone: 1000,
      eligibleEditors: 3,
      eligibleFacesContributors: 3,
      incrementAmount: 3000
    },
    platform: "YouTube",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    requiresEvidence: true,
    effectiveDate
  }),
  seedRule({
    id: "rule-marketing-tiktok-follower-milestone",
    ruleKey: "marketing-tiktok-follower-milestone",
    ruleName: "TikTok Follower Milestone Increment",
    description: "Every follower milestone qualifies top editors and faces/contributors for permanent increment review.",
    department: "Marketing",
    claimType: "Automatic Trigger",
    ruleCategory: "Marketing Milestone",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "follower_milestone",
    triggerMetric: "TikTok followers",
    triggerComparison: "greater_than_or_equal",
    triggerThresholdValue: 5000,
    triggerThresholdUnit: "followers",
    triggerFrequency: "Every milestone",
    automaticTriggerEnabled: true,
    payoutType: "milestone",
    amount: 3000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "salary_milestone",
    formulaKey: "marketing_follower_increment",
    formulaVariables: {
      followerMilestone: 5000,
      eligibleEditors: 3,
      eligibleFacesContributors: 3,
      incrementAmount: 3000
    },
    platform: "TikTok",
    employeeBasedOrTeamBased: "Employee",
    requiresApproval: true,
    requiresEvidence: true,
    effectiveDate
  }),

  seedRule({
    id: "rule-ea-level-1-salary-increment",
    ruleKey: "ea-level-1-salary-increment",
    ruleName: "EA Level 1 Salary Increment",
    description: "EA exam Level 1 approved evidence qualifies for permanent monthly salary increment.",
    department: "EA / Tax Professional",
    claimType: "Employee Claim",
    ruleCategory: "Exam",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "ea_exam_level",
    triggerMetric: "EA Level 1",
    triggerComparison: "completed",
    triggerFrequency: "Once per approved level",
    payoutType: "fixed",
    amount: 15000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_ea_level_increment",
    levelName: "EA Level 1",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "EA Agent Exam Claims and EA agent claim submission are the same thing; do not duplicate.",
    effectiveDate
  }),
  seedRule({
    id: "rule-ea-level-2-salary-increment",
    ruleKey: "ea-level-2-salary-increment",
    ruleName: "EA Level 2 Salary Increment",
    description: "EA exam Level 2 approved evidence qualifies for permanent monthly salary increment.",
    department: "EA / Tax Professional",
    claimType: "Employee Claim",
    ruleCategory: "Exam",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "ea_exam_level",
    triggerMetric: "EA Level 2",
    triggerComparison: "completed",
    triggerFrequency: "Once per approved level",
    payoutType: "fixed",
    amount: 20000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_ea_level_increment",
    levelName: "EA Level 2",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "EA Agent Exam Claims and EA agent claim submission are the same thing; do not duplicate.",
    effectiveDate
  }),
  seedRule({
    id: "rule-ea-level-3-salary-increment",
    ruleKey: "ea-level-3-salary-increment",
    ruleName: "EA Level 3 Salary Increment",
    description: "EA exam Level 3 approved evidence qualifies for permanent monthly salary increment.",
    department: "EA / Tax Professional",
    claimType: "Employee Claim",
    ruleCategory: "Exam",
    incentiveType: "Salary Increment",
    status: "Active",
    isActive: true,
    triggerType: "ea_exam_level",
    triggerMetric: "EA Level 3",
    triggerComparison: "completed",
    triggerFrequency: "Once per approved level",
    payoutType: "fixed",
    amount: 5000,
    currency: "KSH",
    payoutFrequency: "Monthly",
    isPermanentSalaryIncrement: true,
    isCumulative: true,
    isMonthly: true,
    formulaType: "fixed",
    formulaKey: "fixed_ea_level_increment",
    levelName: "EA Level 3",
    employeeBasedOrTeamBased: "Employee",
    requiresEvidence: true,
    requiresApproval: true,
    notes: "EA Agent Exam Claims and EA agent claim submission are the same thing; do not duplicate.",
    effectiveDate
  })
];
